apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: service1.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microservice-1
                port:
                  number: 80

    - host: service2.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microservice-2
                port:
                  number: 80

    - host: service3.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microservice-3
                port:
                  number: 80
