apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: travel-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: memories.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: travel-app-service
                port:
                  number: 80
